# practice python numpy functions


In [5]:
import numpy as np

arr1= np.array([1,2,3,4,5])
print("Array from list : ", arr1)

arr2 = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n", arr2)

arr_arange= np.arange(0,10,2)
print("arrange array:", arr_arange)

arr_linspace= np.linspace(0,10,5)
print("linspace array:", arr_linspace)

arr_zeros = np.zeros((2,3))
print ("zero array:\n", arr_zeros)

arr_ones = np.ones((3,2))
print("ones array: \n", arr_ones )

arr_eye= np.eye(3)
print("identity matrix \n", arr_eye)

Array from list :  [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
arrange array: [0 2 4 6 8]
linspace array: [ 0.   2.5  5.   7.5 10. ]
zero array:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
identity matrix 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# Array Attributes

print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.shape)
print(" Number of dimension:", arr2,np.ndim)
print("Data types:", arr2.dtype)
print("Item size(bytes):", arr2.itemsize)

Shape of arr2 (2, 3)
Size of arr2 (2, 3)
 Number of dimension: [[1 2 3]
 [4 5 6]] <function ndim at 0x7f56efd53420>
Data types: int64
Item size(bytes): 8


In [11]:
arr= np.array([10,20,30,40,50])
print("Original array:",arr)
print("Index2 :",arr[2])
print("last element", arr[-1])
print("Slice 1:4", arr[1:4])

Original array: [10 20 30 40 50]
Index2 : 30
last element 50
Slice 1:4 [20 30 40]


In [15]:
arrd = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array:\n", arrd)
print("First row:",arrd[0,:])
print("Second column:", arrd[:,1])
print("Submatrix:\n",arrd[0:2,1:3])

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
Second column: [2 5 8]
Submatrix:
 [[2 3]
 [5 6]]


In [16]:
a = np.array([1,2,3])
b= np.array([4,5,6])

print("a+b:", a+b)
print("a-b:", a-b)
print("a*b:", a*b)
print("a/b:", a/b)
print("a**b:", a**b)

a+b: [5 7 9]
a-b: [-3 -3 -3]
a*b: [ 4 10 18]
a/b: [0.25 0.4  0.5 ]
a**b: [  1  32 729]


In [17]:
c= np.array([[1,2,3],[4,5,6]])
d = np.array([1,1,1])

print("Broadcasting sum \ n", c+d)

Broadcasting sum \ n [[2 3 4]
 [5 6 7]]


<>:4: SyntaxWarning: invalid escape sequence '\ '
<>:4: SyntaxWarning: invalid escape sequence '\ '
/tmp/ipython-input-546394105.py:4: SyntaxWarning: invalid escape sequence '\ '
  print("Broadcasting sum \ n", c+d)


In [18]:
arr= np.array([1,4,9,16,25])
print("sqrt of array:", np.sqrt(arr))
print("log of array:",np.exp(arr))
print("log", np.log(arr))
print("sin", np.sin(arr))
print("cos",np.cos(arr))



sqrt of array: [1. 2. 3. 4. 5.]
log of array: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
log [0.         1.38629436 2.19722458 2.77258872 3.21887582]
sin [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
cos [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]


In [21]:
arr= np.array([[1,2,3],[4,5,6]])
print("sum", np.sum(arr))
print("Sum axis 0 ", np.sum(arr,axis=0))
print("Sum axis 1 ", np.sum(arr,axis=1))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Argmax:", np.argmax(arr))
print("Argmin:", np.argmin(arr))
print("Standard deviation:", np.std(arr))
print("Variance:", np.var(arr))

sum 21
Sum axis 0  [5 7 9]
Sum axis 1  [ 6 15]
Mean: 3.5
Max: 6
Min: 1
Argmax: 5
Argmin: 0
Standard deviation: 1.707825127659933
Variance: 2.9166666666666665


In [22]:
arr = np.arange(12)
print("Original array:", arr)
arr_reshaped = arr.reshape(3,4)
print("Reshaped 3x4 array:\n", arr_reshaped)
arr_flat = arr_reshaped.flatten()
print("Flattened array:", arr_flat)
arr_transpose = arr_reshaped.T
print("Transpose:\n", arr_transpose)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 3x4 array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Horizontal stack:", np.hstack((a,b)))
print("Vertical stack:\n", np.vstack((a,b)))

arr = np.arange(9)
print("Original array:", arr)
print("Split into 3 parts:", np.split(arr, 3))

Horizontal stack: [1 2 3 4 5 6]
Vertical stack:
 [[1 2 3]
 [4 5 6]]
Original array: [0 1 2 3 4 5 6 7 8]
Split into 3 parts: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [24]:
arr = np.array([10,20,30,40,50])
print("Elements > 25:", arr[arr>25])
indices = [0,2,4]
print("Fancy indexing:", arr[indices])

Elements > 25: [30 40 50]
Fancy indexing: [10 30 50]


In [25]:
rand_arr= np.random.rand(3,3)
print("Random Array:\n",rand_arr)

rand_int = np.random.randint(0,10,15)
print("Random Integer Array:\n",rand_int)


normal_arr= np.random.randn(3,3)
print("Normal Distribution array:\n", normal_arr)


Random Array:
 [[0.14097386 0.25083963 0.23423805]
 [0.39639714 0.97513656 0.03139541]
 [0.49045675 0.72187112 0.12683785]]
Random Integer Array:
 [5 8 6 9 8 2 6 1 1 6 3 2 2 9 4]
Normal Distribution array:
 [[-0.4841769   2.23259025  0.82034019]
 [ 1.31996708  0.82429911  0.07377169]
 [-0.71546052  0.53516124  0.26482838]]


In [26]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Matrix multiplication:\n", np.dot(A,B))
print("Matrix determinant:", np.linalg.det(A))
print("Matrix inverse:\n", np.linalg.inv(A))
print("Eigenvalues and Eigenvectors:\n", np.linalg.eig(A))

Matrix multiplication:
 [[19 22]
 [43 50]]
Matrix determinant: -2.0000000000000004
Matrix inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues and Eigenvectors:
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [27]:
np.save('array.npy', arr)
loaded_arr = np.load('array.npy')
print("Loaded array:", loaded_arr)

print("\n ALl major Numpy function executed successfully !")

Loaded array: [10 20 30 40 50]

 ALl major Numpy function executed successfully !
